import { readFileSync } from 'node:fs';
const DIR = 'C:/Users/droku/AppData/Local/Temp/claude/D--licitapyme-clone/7bff778b-d15c-4340-aeaa-94a8e9fc99bd/scratchpad/anexos1114';
const { abrirDocx, normalizarParaIds, unificarRunsDeMarcadores } = await import('@/app/lib/anexos-docx');
const { analizarAnexo } = await import('@/app/lib/anexos-detectar');
const buf = readFileSync(`${DIR}/ANEXO_N°_2-A_+_ANEXO_N°_2-B.docx`);
const { xml } = await abrirDocx(buf);
const { xml: conIds } = normalizarParaIds(xml);
const norm = unificarRunsDeMarcadores(conIds);
const an = analizarAnexo(norm, {});
console.log('candidatosCelda con "Teléfono":');
for (const c of an.candidatosCelda) if (/tel[eé]fono/i.test(c.etiqueta)) console.log(' ', JSON.stringify(c));
console.log('camposConDosPuntos con "Teléfono":');
for (const c of an.camposConDosPuntos) if (/tel[eé]fono/i.test(c.etiqueta)) console.log(' ', JSON.stringify(c));
console.log('total párrafos:', an.parrafos.length);
const idxCorreo = an.parrafos.findIndex(p => /Correo Electr.*Contacto/i.test(p.texto));
console.log('párrafos alrededor del de Correo (idx', idxCorreo, '):');
for (let i = Math.max(0, idxCorreo - 1); i <= idxCorreo + 4; i++) console.log(`  [${i}] vacio=${an.parrafos[i]?.vacio} "${(an.parrafos[i]?.texto||'').slice(0,50)}"`);
console.log('\ncamposConDosPuntos con "Correo":');
for (const c of an.camposConDosPuntos) if (/correo/i.test(c.etiqueta)) console.log(' ', JSON.stringify(c));
console.log('\ncandidatosCeldaSinDesambiguar con "Tel|Correo":');
for (const c of (an as any).candidatosCeldaSinDesambiguar ?? []) if (/tel[eé]fono|correo/i.test(c.etiqueta)) console.log(' ', JSON.stringify(c));
